### ISSUE TITLE
UTF8 error with french windows 2012

### ISSUE THREAD

**Issue by dominiquearpin** [voxpupuli/puppet-windowsfeature#109]
The module seem to have some problem with UTF8 encoding...

Puppet 5.3.3

Error: Failed to apply catalog: #<ArgumentError: invalid byte sequence in UTF-8>

C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.4.0/rexml/source.rb:220:in `match'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.4.0/rexml/source.rb:220:in `match'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.4.0/rexml/parsers/baseparser.rb:427:in `pull_event'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.4.0/rexml/parsers/baseparser.rb:185:in `pull'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.4.0/rexml/parsers/treeparser.rb:23:in `parse'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.4.0/rexml/document.rb:288:in `build'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.4.0/rexml/document.rb:45:in `initialize'
C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet/provider/windowsfeature/default.rb:31:in `new'
C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet/provider/windowsfeature/default.rb:31:in `instances'
C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet/provider/windowsfeature/default.rb:54:in `prefetch'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/transaction.rb:340:in `prefetch'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/transaction.rb:241:in `prefetch_if_necessary'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/transaction.rb:107:in `block in evaluate'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/graph/relationship_graph.rb:119:in `traverse'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/transaction.rb:169:in `evaluate'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:225:in `block in apply'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/util/log.rb:155:in `with_destination'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/transaction/report.rb:140:in `as_logging_destination'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:224:in `apply'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/configurer.rb:172:in `block in apply_catalog'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/util.rb:224:in `block in benchmark'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.4.0/benchmark.rb:308:in`realtime'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/util.rb:223:in `benchmark'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/configurer.rb:171:in `apply_catalog'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/configurer.rb:344:in `run_internal'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/configurer.rb:222:in `block in run'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/context.rb:65:in `override'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet.rb:263:in `override'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/configurer.rb:196:in `run'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/agent.rb:46:in `block (4 levels) in run'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/agent/locker.rb:21:in `lock'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/agent.rb:46:in `block (3 levels) in run'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/agent.rb:110:in `with_client'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/agent.rb:43:in `block (2 levels) in run'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/agent.rb:67:in `run_in_fork'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/agent.rb:42:in `block in run'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/application.rb:179:in `controlled_run'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/agent.rb:40:in `run'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/application/agent.rb:365:in `onetime'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/application/agent.rb:343:in `run_command'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/application.rb:358:in `block in run'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/util.rb:666:in `exit_on_fail'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/application.rb:358:in `run'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/util/command_line.rb:132:in `run'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/util/command_line.rb:72:in `execute'
C:/Program Files/Puppet Labs/Puppet/puppet/bin/puppet:4:in `<main>'
...
Exception parsing
Line: 5
Position: 154
Last 80 unconsumed characters:
Accès à distance</Property>

C:\windows\system32>

**Comment by TraGicCode** [comment]
Hey @dominiquearpin , Can you try this PR and see if it resolves your issue #112

**Comment by TraGicCode** [comment]
This has been resolved in #112
