### ISSUE TITLE
The restart parameter has been deprecated in favor of the puppetlabs reboot module ( https://github.com/puppetlabs/puppetlabs-reboot ). This parameter will be removed in the next release.  (location: C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet/type/windowsfeature.rb:20:in `block (2 levels) in <top (required)>') shows every run

### ISSUE THREAD

**Issue by rychannel** [voxpupuli/puppet-windowsfeature#120]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.3 (2018.1.2)
- Ruby:
- Distribution:
- Module version: 3.2.0

## What are you seeing

Every run on the Puppet Agent displays the following error message 
"The restart parameter has been deprecated in favor of the puppetlabs reboot module ( https://github.com/puppetlabs/puppetlabs-reboot ). This parameter will be removed in the next release.

(location: C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet/type/windowsfeature.rb:20:in `block (2 levels) in <top (required)>')"

## What behaviour did you expect instead
I'd expect this message to show if I was using the restart parameter anywhere.  But I'm not and this message shows up on all of my servers with every run

**Comment by rychannel** [comment]
Really my main issue, is that its causing panic when folks that don't understand Puppet see this in the event viewer on servers and think Puppet is restarting their servers every 1/2 hour.

Also, I don't like being constantly warned about something I'm not using.

**Comment by rychannel** [comment]
What version will the fix be available in Puppet Forge?

**Comment by TraGicCode** [comment]
The latest version will have this now.
