### ISSUE TITLE
Version release

### ISSUE THREAD

**Issue by ic248** [voxpupuli/puppet-windowsfeature#157]
Hi,

Do you have an ETA of when the next version will be released? We're planning to upgrade to Puppet 8 and I can see that the the current release (4.0.0) doesn't support Puppet 8. It looks like with some of the latest PRs Puppet 8 is supported #155 . 

Thanks
Ian

**Comment by td-adc** [comment]
Any updates on this?

**Comment by ic248** [comment]
Afraid not, got told in the Slack channel to test and see if it works with the current version (which it does) but couldn't get anyone to release a new version. I'm currently using the release version even though it doesn't state that it's Puppet 8 compatible
