### ISSUE TITLE
Refactor into type and provider

### ISSUE THREAD

**Issue by petems** [voxpupuli/puppet-windowsfeature#43]
Looks like @matthewrstone has done a lot of work on this already :smile: 

https://github.com/matthewrstone/puppet-windowsfeature/tree/33-create_type_and_provider

Would also fix the performance issues with an array of features (#53)

**Comment by matthewrstone** [comment]
I'd be happy to hack away at this some more if additional functionality is required...I just need some guidance for writing the tests.

**Comment by petems** [comment]
@matthewrstone Awesome, I can help with that, I've done a few tests for my swap_file type and provider: 

https://github.com/petems/puppet-swap_file/blob/type_provider_refactor/spec/unit/puppet/provider/swap_file/linux_spec.rb

**Comment by petems** [comment]
@matthewrstone did some quick work with some basic boilerplate for type and provider unit tests:

https://github.com/puppet-community/puppet-windowsfeature/tree/type_provider_refactor

Thoughts?

**Comment by petems** [comment]
Closed by #47
