### ISSUE TITLE
Git Release 2.0.0 does not point to latest code in repository

### ISSUE THREAD

**Issue by maxgaulhofer** [voxpupuli/puppet-windowsfeature#61]
When I download this repo via the following link `https://github.com/voxpupuli/puppet-windowsfeature/archive/v2.0.0.zip` it does not download the latest version the repository.

The file `default.rb` still contains ConvertTo-JSON instead of ConvertTo-XML

I think the release 2.0.0 is not created properly

**Comment by tkishel** [comment]
Currently, forge.puppet.com lists v 2.0.0 while github lists v 2.0.2, and lists it under puppet/puppet-windowsfeature instead of voxpupuli/puppet-windowsfeature

**Comment by wyardley** [comment]
I think this can be closed, since there have been multiple releases since then. Let us know if there are still problems with GitHub downloads.
