### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by lfarnell** [voxpupuli/puppet-windowsfeature#89]
With the merging of https://github.com/voxpupuli/puppet-windowsfeature/pull/88, I find now I can use this module to install windowsfeatures on Win2k8 R2. Would it be possible to create a new release to include this change? Thanks!

**Comment by wyardley** [comment]
3.0.0 is being cut (#95)

**Comment by TraGicCode** [comment]
Released to the forge!
