### ISSUE TITLE
Fix README and check on license

### ISSUE THREAD

**Issue by wyardley** [voxpupuli/puppet-windowsfeature#96]
The Readme could use some fixes:

- [x] The readme needs to be reviewed to ensure it's up-to-date with the actual code.
- [x] Some of the markdown in README.md needs to be fixed.
- [x] Badges should be updated to match other vox modules. ( https://github.com/voxpupuli/puppet-rabbitmq )
- [x] CONTRIBUTING.md might need synced with `.github/CONTRIBUTING.md`?

**Comment by alexjfisher** [comment]
LICENSE is fine I think.  github license detection works and it matches the metadata.

**Comment by TraGicCode** [comment]
@wyardley I have updated your issue by creating a list of tasks.  I'll start working on these.

**Comment by TraGicCode** [comment]
@wyardley  I see the old contributing.md at the root of this repo and the one from modulesync in the .github directory like you state.  i'm confused on what you mean "sync"ing them.  Is the an automated process?

**Comment by wyardley** [comment]
@TraGicCode https://github.com/voxpupuli/modulesync_config/issues/252
many modules only have `.github/CONTRIBUTING.md` currently. In cases where there's a copy in the root, modulesync currently doesn't do anything, so yes, we'd have to manually update it.

**Comment by wyardley** [comment]
Do we think 2016 support is just a metadata bump (#83)? Or does more testing / work need to be done?

**Comment by TraGicCode** [comment]
I think it works but let's not bump it just yet.  I have my own windows 2016 box I use.



Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone


-------- Original message --------
